sites = {
    'FOLC1L': 'FLOW-LOC',
    'FOLC1F': 'FLOW-NAT',
    'NFDC1': 'FLOW-IN',
    'FMDC1': 'FLOW-IN',
    'HLLC1F': 'FLOW-NAT',
    'RBBC1F': 'FLOW-NAT',
    'HLLC1L': 'FLOW-LOC',
    'UNVC1F': 'FLOW-NAT',
    'LNLC1F': 'FLOW-NAT',
    'RRGC1F': 'FLOW-NAT',
    'ICHC1F': 'FLOW-NAT',
    'SVCC1L': 'FLOW-LOC',
    'MFAC1L': 'FLOW-LOC',
    'MFPC1L': 'FLOW-LOC',
    'DUMMY': 'FLOW',
    # 'LOCAL_SF FOLC1L': 'FLOW-LOC',
    'RRGC1L': 'FLOW-LOC',
    # 'SPYC1F': 'FLOW-NAT',
    'RUFC1L': 'FLOW-LOC',
    'AKYC1': 'FLOW-IN',
    'CBAC1L': 'FLOW-LOC',
    'NMFC1': 'FLOW-IN',
    # 'LOCAL_NF FOLC1L': 'FLOW-LOC',
    'MFAC1F': 'FLOW-NAT',
    'CBAC1F': 'FLOW-NAT',
    'MFPC1F': 'FLOW-NAT',
    'RUFC1F': 'FLOW-NAT',
    # 'MFAC1':'FLOW', 
    # 'SVCC1':'FLOW', 
    # 'RUFC1':'FLOW', 
    # 'RRGC1':'FLOW', 
    # 'LNLC1':'FLOW', 
    # 'RBBC1':'FLOW', 
    # 'CBAC1':'FLOW', 
    # 'ICHC1':'FLOW', 
    # 'FOLC1':'FLOW', 
    # 'UNVC1':'FLOW', 
    # 'HLLC1':'FLOW',
    'SPYC1':'FLOW'
}